version: '3.8'

# Windows özel Docker Compose yapılandırması
# Serial port desteği Windows'da farklı şekilde çalışır

services:
  pcba-test:
    build: .
    container_name: pcba-test-system
    ports:
      - "9002:9002"      # Web arayüzü portu  
      - "502:502"        # Modbus TCP portu
    volumes:
      - ./data:/app/data # Veritabanı persistent storage
      - ./dash:/app/dash # Template dosyaları live reload
    environment:
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - DATABASE_PATH=/app/data/pcba_test.db
    restart: unless-stopped
    networks:
      - pcba-network

  # Windows Serial Port Bridge (gerekirse)
  # Serial portlar için ayrı bir Windows service gerekebilir
  # Bu durumda TCP-Serial bridge kullanılabilir

networks:
  pcba-network:
    driver: bridge

# Not: Windows'da serial port erişimi daha karmaşıktır
# Alternatif çözümler:
# 1. TCP-Serial bridge kullanın (ser2net benzeri)
# 2. Host bilgisayarda bir serial proxy çalıştırın
# 3. USB-over-IP çözümü kullanın